[Paths]
repos_path = /home/gustavo/Projetos/axok-os/aopm/repos
modules_path = /home/gustavo/Projetos/axok-os/aopm/src/modules
repos_index_path = /home/gustavo/Projetos/axok-os/aopm/lib/repos
keys_path = /home/gustavo/Projetos/axok-os/aopm/keys
packages_path = /home/gustavo/Projetos/axok-os/aopm/packages_dir